name: Deploy
on:
  push:
    branches:
      - 'main'

jobs:
  conditional_step:
    runs-on: 'ubuntu-20.04'
    steps:
    - name: Checkout resources repo
      uses: actions/checkout@v2
      with:
        ref: main
        repository: runawaybon/demo-web-app
        path: ./resources
        
    - name: Checkout self repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        path: ./source
        
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - run: |
        cd /home/runner/work/demo-web-api/demo-web-api/source/
        ls
        pwd
        mvn compile exec:java -Dsource="/home/runner/work/demo-web-api/demo-web-api/resources/"
